name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo -e ${{ secrets.ENV_FILE }} | base64 --decode > .env
          

      - name: Print .env file contents
        run: cat .env
        shell: bash
