name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo ${{ secrets.ENV_FILE }} >> .env

      - name: Print .env file contents
        run: cat README.md
        shell: bash 
