name: Example Workflow

on:
  push:
    tags:
      - '*'

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print tag name
        run: echo "The tag name is ${GITHUB_REF#refs/tags/}"
