name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          PGSQL_CONNINFO: ${{ secrets.PGSQL_CONNINFO }}
          CHAINLIT_AUTH_SECRET: ${{ secrets.CHAINLIT_AUTH_SECRET }}
          NEO4J_URI: ${{ secrets.NEO4J_URI }}
          

      - name: Print .env file contents
        run: cat .env
