name: Example Workflow

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set github.ref_name
        run: echo "GITHUB_REF_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Print github.ref_name
        run: echo "The ref name is $GITHUB_REF_NAME"
